// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RobRequest.Shared.Data;

#nullable disable

namespace RobRequest.Shared.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260627210451_AddShowLineNumbersToUserSettings")]
    partial class AddShowLineNumbersToUserSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("RobRequest.Shared.Models.CollectionModel", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("ParentId");

                    b.HasIndex("UserId");

                    b.ToTable("Collections");
                });

            modelBuilder.Entity("RobRequest.Shared.Models.CollectionRequestModel", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("CollectionId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CollectionId");

                    b.ToTable("CollectionRequests");
                });

            modelBuilder.Entity("RobRequest.Shared.Models.EnvironmentModel", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("UserId");

                    b.ToTable("Environments");
                });

            modelBuilder.Entity("RobRequest.Shared.Models.HistoryItem", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<long>("ResponseTimeMs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("Url");

                    b.HasIndex("UserId");

                    b.ToTable("HistoryItems");
                });

            modelBuilder.Entity("RobRequest.Shared.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RobRequest.Shared.Models.UserGroup", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("UserGroups");
                });

            modelBuilder.Entity("RobRequest.Shared.Models.UserSettings", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("ActiveEnvironmentId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<bool>("AutoFormatJson")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DarkMode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DefaultTimeoutSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("FollowRedirects")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxHistoryItems")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowLineNumbers")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<bool>("ValidateSslCertificates")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserSettings");
                });

            modelBuilder.Entity("RobRequest.Shared.Models.CollectionModel", b =>
                {
                    b.HasOne("RobRequest.Shared.Models.CollectionModel", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("RobRequest.Shared.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RobRequest.Shared.Models.CollectionRequestModel", b =>
                {
                    b.HasOne("RobRequest.Shared.Models.CollectionModel", "Collection")
                        .WithMany("Requests")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("RobRequest.Shared.Models.HttpRequestModel", "Request", b1 =>
                        {
                            b1.Property<string>("CollectionRequestModelId");

                            b1.Property<string>("Body")
                                .IsRequired();

                            b1.Property<string>("BodyType")
                                .IsRequired();

                            b1.Property<string>("ContentType")
                                .IsRequired();

                            b1.Property<DateTime>("CreatedAt");

                            b1.Property<string>("Id")
                                .IsRequired()
                                .HasMaxLength(36);

                            b1.Property<string>("Method")
                                .IsRequired()
                                .HasMaxLength(7);

                            b1.Property<int>("TimeoutSeconds");

                            b1.Property<string>("Url")
                                .IsRequired();

                            b1.HasKey("CollectionRequestModelId");

                            b1.ToTable("CollectionRequests");

                            b1
                                .ToJson("Request")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("CollectionRequestModelId");

                            b1.OwnsOne("RobRequest.Shared.Models.AuthSettings", "Auth", b2 =>
                                {
                                    b2.Property<string>("HttpRequestModelCollectionRequestModelId");

                                    b2.Property<int>("ApiKeyLocation");

                                    b2.Property<string>("ApiKeyName")
                                        .IsRequired();

                                    b2.Property<string>("ApiKeyValue")
                                        .IsRequired();

                                    b2.Property<string>("AuthPassword")
                                        .IsRequired();

                                    b2.Property<string>("AuthToken")
                                        .IsRequired();

                                    b2.Property<int>("AuthType");

                                    b2.Property<string>("AuthUsername")
                                        .IsRequired();

                                    b2.Property<bool>("OAuth2AutoRefresh");

                                    b2.Property<string>("OAuth2ClientId")
                                        .IsRequired();

                                    b2.Property<string>("OAuth2ClientSecret")
                                        .IsRequired();

                                    b2.Property<int>("OAuth2GrantType");

                                    b2.Property<string>("OAuth2Scope")
                                        .IsRequired();

                                    b2.Property<DateTime?>("OAuth2TokenExpiresAt");

                                    b2.Property<string>("OAuth2TokenUrl")
                                        .IsRequired();

                                    b2.HasKey("HttpRequestModelCollectionRequestModelId");

                                    b2.ToTable("CollectionRequests");

                                    b2.WithOwner()
                                        .HasForeignKey("HttpRequestModelCollectionRequestModelId");
                                });

                            b1.OwnsMany("RobRequest.Shared.Models.FormDataItem", "FormData", b2 =>
                                {
                                    b2.Property<string>("HttpRequestModelCollectionRequestModelId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAddOrUpdate();

                                    b2.Property<string>("ContentType");

                                    b2.Property<bool>("Enabled");

                                    b2.Property<string>("FileName");

                                    b2.Property<bool>("IsFile");

                                    b2.Property<string>("Key")
                                        .IsRequired();

                                    b2.Property<string>("Value")
                                        .IsRequired();

                                    b2.HasKey("HttpRequestModelCollectionRequestModelId", "__synthesizedOrdinal");

                                    b2.ToTable("CollectionRequests");

                                    b2.WithOwner()
                                        .HasForeignKey("HttpRequestModelCollectionRequestModelId");
                                });

                            b1.OwnsMany("RobRequest.Shared.Models.HeaderItem", "Headers", b2 =>
                                {
                                    b2.Property<string>("HttpRequestModelCollectionRequestModelId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAddOrUpdate();

                                    b2.Property<bool>("Enabled");

                                    b2.Property<string>("Key")
                                        .IsRequired();

                                    b2.Property<string>("Value")
                                        .IsRequired();

                                    b2.HasKey("HttpRequestModelCollectionRequestModelId", "__synthesizedOrdinal");

                                    b2.ToTable("CollectionRequests");

                                    b2.WithOwner()
                                        .HasForeignKey("HttpRequestModelCollectionRequestModelId");
                                });

                            b1.OwnsMany("RobRequest.Shared.Models.QueryParamItem", "QueryParams", b2 =>
                                {
                                    b2.Property<string>("HttpRequestModelCollectionRequestModelId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAddOrUpdate();

                                    b2.Property<bool>("Enabled");

                                    b2.Property<string>("Key")
                                        .IsRequired();

                                    b2.Property<string>("Value")
                                        .IsRequired();

                                    b2.HasKey("HttpRequestModelCollectionRequestModelId", "__synthesizedOrdinal");

                                    b2.ToTable("CollectionRequests");

                                    b2.WithOwner()
                                        .HasForeignKey("HttpRequestModelCollectionRequestModelId");
                                });

                            b1.Navigation("Auth")
                                .IsRequired();

                            b1.Navigation("FormData");

                            b1.Navigation("Headers");

                            b1.Navigation("QueryParams");
                        });

                    b.Navigation("Collection");

                    b.Navigation("Request")
                        .IsRequired();
                });

            modelBuilder.Entity("RobRequest.Shared.Models.EnvironmentModel", b =>
                {
                    b.HasOne("RobRequest.Shared.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("RobRequest.Shared.Models.AuthSettings", "Auth", b1 =>
                        {
                            b1.Property<string>("EnvironmentModelId");

                            b1.Property<int>("ApiKeyLocation");

                            b1.Property<string>("ApiKeyName")
                                .IsRequired();

                            b1.Property<string>("ApiKeyValue")
                                .IsRequired();

                            b1.Property<string>("AuthPassword")
                                .IsRequired();

                            b1.Property<string>("AuthToken")
                                .IsRequired();

                            b1.Property<int>("AuthType");

                            b1.Property<string>("AuthUsername")
                                .IsRequired();

                            b1.Property<bool>("OAuth2AutoRefresh");

                            b1.Property<string>("OAuth2ClientId")
                                .IsRequired();

                            b1.Property<string>("OAuth2ClientSecret")
                                .IsRequired();

                            b1.Property<int>("OAuth2GrantType");

                            b1.Property<string>("OAuth2Scope")
                                .IsRequired();

                            b1.Property<DateTime?>("OAuth2TokenExpiresAt");

                            b1.Property<string>("OAuth2TokenUrl")
                                .IsRequired();

                            b1.HasKey("EnvironmentModelId");

                            b1.ToTable("Environments");

                            b1
                                .ToJson("Auth")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("EnvironmentModelId");
                        });

                    b.OwnsMany("RobRequest.Shared.Models.EnvironmentVariable", "Variables", b1 =>
                        {
                            b1.Property<string>("EnvironmentModelId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<bool>("Enabled");

                            b1.Property<bool>("IsSecret");

                            b1.Property<string>("Key")
                                .IsRequired()
                                .HasMaxLength(50);

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255);

                            b1.HasKey("EnvironmentModelId", "__synthesizedOrdinal");

                            b1.ToTable("Environments");

                            b1
                                .ToJson("Variables")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("EnvironmentModelId");
                        });

                    b.Navigation("Auth")
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Variables");
                });

            modelBuilder.Entity("RobRequest.Shared.Models.HistoryItem", b =>
                {
                    b.HasOne("RobRequest.Shared.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("RobRequest.Shared.Models.HttpRequestModel", "Request", b1 =>
                        {
                            b1.Property<string>("HistoryItemId");

                            b1.Property<string>("Body")
                                .IsRequired();

                            b1.Property<string>("BodyType")
                                .IsRequired();

                            b1.Property<string>("ContentType")
                                .IsRequired();

                            b1.Property<DateTime>("CreatedAt");

                            b1.Property<string>("Id")
                                .IsRequired()
                                .HasMaxLength(36);

                            b1.Property<string>("Method")
                                .IsRequired()
                                .HasMaxLength(7);

                            b1.Property<int>("TimeoutSeconds");

                            b1.Property<string>("Url")
                                .IsRequired();

                            b1.HasKey("HistoryItemId");

                            b1.ToTable("HistoryItems");

                            b1
                                .ToJson("Request")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("HistoryItemId");

                            b1.OwnsOne("RobRequest.Shared.Models.AuthSettings", "Auth", b2 =>
                                {
                                    b2.Property<string>("HttpRequestModelHistoryItemId");

                                    b2.Property<int>("ApiKeyLocation");

                                    b2.Property<string>("ApiKeyName")
                                        .IsRequired();

                                    b2.Property<string>("ApiKeyValue")
                                        .IsRequired();

                                    b2.Property<string>("AuthPassword")
                                        .IsRequired();

                                    b2.Property<string>("AuthToken")
                                        .IsRequired();

                                    b2.Property<int>("AuthType");

                                    b2.Property<string>("AuthUsername")
                                        .IsRequired();

                                    b2.Property<bool>("OAuth2AutoRefresh");

                                    b2.Property<string>("OAuth2ClientId")
                                        .IsRequired();

                                    b2.Property<string>("OAuth2ClientSecret")
                                        .IsRequired();

                                    b2.Property<int>("OAuth2GrantType");

                                    b2.Property<string>("OAuth2Scope")
                                        .IsRequired();

                                    b2.Property<DateTime?>("OAuth2TokenExpiresAt");

                                    b2.Property<string>("OAuth2TokenUrl")
                                        .IsRequired();

                                    b2.HasKey("HttpRequestModelHistoryItemId");

                                    b2.ToTable("HistoryItems");

                                    b2.WithOwner()
                                        .HasForeignKey("HttpRequestModelHistoryItemId");
                                });

                            b1.OwnsMany("RobRequest.Shared.Models.FormDataItem", "FormData", b2 =>
                                {
                                    b2.Property<string>("HttpRequestModelHistoryItemId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAddOrUpdate();

                                    b2.Property<string>("ContentType");

                                    b2.Property<bool>("Enabled");

                                    b2.Property<string>("FileName");

                                    b2.Property<bool>("IsFile");

                                    b2.Property<string>("Key")
                                        .IsRequired();

                                    b2.Property<string>("Value")
                                        .IsRequired();

                                    b2.HasKey("HttpRequestModelHistoryItemId", "__synthesizedOrdinal");

                                    b2.ToTable("HistoryItems");

                                    b2.WithOwner()
                                        .HasForeignKey("HttpRequestModelHistoryItemId");
                                });

                            b1.OwnsMany("RobRequest.Shared.Models.HeaderItem", "Headers", b2 =>
                                {
                                    b2.Property<string>("HttpRequestModelHistoryItemId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAddOrUpdate();

                                    b2.Property<bool>("Enabled");

                                    b2.Property<string>("Key")
                                        .IsRequired();

                                    b2.Property<string>("Value")
                                        .IsRequired();

                                    b2.HasKey("HttpRequestModelHistoryItemId", "__synthesizedOrdinal");

                                    b2.ToTable("HistoryItems");

                                    b2.WithOwner()
                                        .HasForeignKey("HttpRequestModelHistoryItemId");
                                });

                            b1.OwnsMany("RobRequest.Shared.Models.QueryParamItem", "QueryParams", b2 =>
                                {
                                    b2.Property<string>("HttpRequestModelHistoryItemId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAddOrUpdate();

                                    b2.Property<bool>("Enabled");

                                    b2.Property<string>("Key")
                                        .IsRequired();

                                    b2.Property<string>("Value")
                                        .IsRequired();

                                    b2.HasKey("HttpRequestModelHistoryItemId", "__synthesizedOrdinal");

                                    b2.ToTable("HistoryItems");

                                    b2.WithOwner()
                                        .HasForeignKey("HttpRequestModelHistoryItemId");
                                });

                            b1.Navigation("Auth")
                                .IsRequired();

                            b1.Navigation("FormData");

                            b1.Navigation("Headers");

                            b1.Navigation("QueryParams");
                        });

                    b.OwnsOne("RobRequest.Shared.Models.HttpResponseModel", "Response", b1 =>
                        {
                            b1.Property<string>("HistoryItemId");

                            b1.Property<string>("Body")
                                .IsRequired();

                            b1.Property<string>("ContentType")
                                .IsRequired();

                            b1.Property<string>("ErrorMessage");

                            b1.Property<DateTime>("ReceivedAt");

                            b1.Property<long>("ResponseSizeBytes");

                            b1.Property<long>("ResponseTimeMs");

                            b1.Property<string>("StackTrace");

                            b1.Property<int>("StatusCode");

                            b1.Property<string>("StatusText")
                                .IsRequired();

                            b1.HasKey("HistoryItemId");

                            b1.ToTable("HistoryItems");

                            b1
                                .ToJson("Response")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("HistoryItemId");

                            b1.OwnsMany("RobRequest.Shared.Models.HeaderItem", "Headers", b2 =>
                                {
                                    b2.Property<string>("HttpResponseModelHistoryItemId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAddOrUpdate();

                                    b2.Property<bool>("Enabled");

                                    b2.Property<string>("Key")
                                        .IsRequired();

                                    b2.Property<string>("Value")
                                        .IsRequired();

                                    b2.HasKey("HttpResponseModelHistoryItemId", "__synthesizedOrdinal");

                                    b2.ToTable("HistoryItems");

                                    b2.WithOwner()
                                        .HasForeignKey("HttpResponseModelHistoryItemId");
                                });

                            b1.Navigation("Headers");
                        });

                    b.Navigation("Request");

                    b.Navigation("Response");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RobRequest.Shared.Models.User", b =>
                {
                    b.HasOne("RobRequest.Shared.Models.UserGroup", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("RobRequest.Shared.Models.UserSettings", b =>
                {
                    b.HasOne("RobRequest.Shared.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RobRequest.Shared.Models.CollectionModel", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Requests");
                });
#pragma warning restore 612, 618
        }
    }
}
