// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RobRequest.Shared.Data;

#nullable disable

namespace RobRequest.Shared.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.4");

            modelBuilder.Entity("RobRequest.Shared.Models.HistoryItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ResponseTimeMs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("Url");

                    b.ToTable("HistoryItems");
                });

            modelBuilder.Entity("RobRequest.Shared.Models.UserSettings", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActiveEnvironmentId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("AutoFormatJson")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DarkMode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DefaultTimeoutSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("FollowRedirects")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxHistoryItems")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ValidateSslCertificates")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("UserSettings");
                });

            modelBuilder.Entity("RobRequest.Shared.Models.HistoryItem", b =>
                {
                    b.OwnsOne("RobRequest.Shared.Models.HttpRequestModel", "Request", b1 =>
                        {
                            b1.Property<string>("HistoryItemId");

                            b1.Property<int>("ApiKeyLocation");

                            b1.Property<string>("ApiKeyName")
                                .IsRequired();

                            b1.Property<string>("ApiKeyValue")
                                .IsRequired();

                            b1.Property<string>("AuthPassword")
                                .IsRequired();

                            b1.Property<string>("AuthToken")
                                .IsRequired();

                            b1.Property<int>("AuthType");

                            b1.Property<string>("AuthUsername")
                                .IsRequired();

                            b1.Property<string>("Body")
                                .IsRequired();

                            b1.Property<string>("BodyType")
                                .IsRequired();

                            b1.Property<string>("ContentType")
                                .IsRequired();

                            b1.Property<DateTime>("CreatedAt");

                            b1.Property<string>("Id");

                            b1.Property<string>("Method")
                                .IsRequired();

                            b1.Property<int>("TimeoutSeconds");

                            b1.Property<string>("Url")
                                .IsRequired();

                            b1.HasKey("HistoryItemId");

                            b1.ToTable("HistoryItems");

                            b1
                                .ToJson("Request")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("HistoryItemId");

                            b1.OwnsMany("RobRequest.Shared.Models.FormDataItem", "FormData", b2 =>
                                {
                                    b2.Property<string>("HttpRequestModelHistoryItemId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAddOrUpdate();

                                    b2.Property<string>("ContentType");

                                    b2.Property<bool>("Enabled");

                                    b2.Property<string>("FileName");

                                    b2.Property<bool>("IsFile");

                                    b2.Property<string>("Key")
                                        .IsRequired();

                                    b2.Property<string>("Value")
                                        .IsRequired();

                                    b2.HasKey("HttpRequestModelHistoryItemId", "__synthesizedOrdinal");

                                    b2.ToTable("HistoryItems");

                                    b2.WithOwner()
                                        .HasForeignKey("HttpRequestModelHistoryItemId");
                                });

                            b1.OwnsMany("RobRequest.Shared.Models.HeaderItem", "Headers", b2 =>
                                {
                                    b2.Property<string>("HttpRequestModelHistoryItemId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAddOrUpdate();

                                    b2.Property<bool>("Enabled");

                                    b2.Property<string>("Key")
                                        .IsRequired();

                                    b2.Property<string>("Value")
                                        .IsRequired();

                                    b2.HasKey("HttpRequestModelHistoryItemId", "__synthesizedOrdinal");

                                    b2.ToTable("HistoryItems");

                                    b2.WithOwner()
                                        .HasForeignKey("HttpRequestModelHistoryItemId");
                                });

                            b1.OwnsMany("RobRequest.Shared.Models.QueryParamItem", "QueryParams", b2 =>
                                {
                                    b2.Property<string>("HttpRequestModelHistoryItemId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAddOrUpdate();

                                    b2.Property<bool>("Enabled");

                                    b2.Property<string>("Key")
                                        .IsRequired();

                                    b2.Property<string>("Value")
                                        .IsRequired();

                                    b2.HasKey("HttpRequestModelHistoryItemId", "__synthesizedOrdinal");

                                    b2.ToTable("HistoryItems");

                                    b2.WithOwner()
                                        .HasForeignKey("HttpRequestModelHistoryItemId");
                                });

                            b1.Navigation("FormData");

                            b1.Navigation("Headers");

                            b1.Navigation("QueryParams");
                        });

                    b.OwnsOne("RobRequest.Shared.Models.HttpResponseModel", "Response", b1 =>
                        {
                            b1.Property<string>("HistoryItemId");

                            b1.Property<string>("Body")
                                .IsRequired();

                            b1.Property<string>("ContentType")
                                .IsRequired();

                            b1.Property<string>("ErrorMessage");

                            b1.Property<DateTime>("ReceivedAt");

                            b1.Property<long>("ResponseSizeBytes");

                            b1.Property<long>("ResponseTimeMs");

                            b1.Property<int>("StatusCode");

                            b1.Property<string>("StatusText")
                                .IsRequired();

                            b1.HasKey("HistoryItemId");

                            b1.ToTable("HistoryItems");

                            b1
                                .ToJson("Response")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("HistoryItemId");

                            b1.OwnsMany("RobRequest.Shared.Models.HeaderItem", "Headers", b2 =>
                                {
                                    b2.Property<string>("HttpResponseModelHistoryItemId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAddOrUpdate();

                                    b2.Property<bool>("Enabled");

                                    b2.Property<string>("Key")
                                        .IsRequired();

                                    b2.Property<string>("Value")
                                        .IsRequired();

                                    b2.HasKey("HttpResponseModelHistoryItemId", "__synthesizedOrdinal");

                                    b2.ToTable("HistoryItems");

                                    b2.WithOwner()
                                        .HasForeignKey("HttpResponseModelHistoryItemId");
                                });

                            b1.Navigation("Headers");
                        });

                    b.Navigation("Request");

                    b.Navigation("Response");
                });
#pragma warning restore 612, 618
        }
    }
}
